### ISSUE TITLE
language filter option does not work

### ISSUE THREAD

**Issue by zer0-t** [tampe125/hashtag-scraper#3]
Hi tampe125,

Great tool you made love it! but i found a bug when using the --l option with the language code **nl** which stand for the Dutch lang no output is shown.
I also tried it with the language code **de**.

When running your tool without any options within a couple of minutes the first 100 words are fetched. when running it with the -l nl option it is stuck on the text "14:25:33|[INFO] Got stream, starting to analyze tweets"

Thanks in advance.

**Comment by tampe125** [comment]
Hello,

thank you very much for using this tool.
Regarding the language filter, you should consider that we are analyzing the **whole** feed of **all** tweets. This means that non-english languages are a small percentage of the whole feed.
Moreover Twitter is known to report the incorrect language, I suspect it is related to the position of the user, not the real language used.
Finally, please remember that we are applying several filters:
1. The tweet has to be in NL (or DE)
2. There must be at least one hashtag
3. Such hashtag must be at least 10 chars long (or the length you passed as argument)

So that's totally possible to get only few words after some time: you have to let it run longer. For your information, when you kill the process by hitting CTRL+C you will write to disk all the hashtags you found so far.
